### PR TITLE
Added FAQ section for crashing on direct message

### LINKED ISSUE #86: On desktop notification the App Crashes
Hi, i have a problem. When i receive a desktop notification, the app crashes, in the console does not appear any message

I read this issue and update my browser but the problem continues
https://github.com/plaidchat/plaidchat/issues/76

Information about OS:
npm --version: 2.11.3
node --version: v0.12.4
OS: 4.0.5-1-ARCH
Gnome Shell 3.16.2
Chrome Versión 43.0.2357.130 (64-bit)
slack-for-linux Version 2.0.1

Regards.

### PR DESCRIPTION
**Pull request by twolfson**
We have received our second report for crashes when `libffmpegsumo.so` is out of date. In order to decrease the amount of issues, we are adding another FAQ to the README. In this PR:

- Added "Crashing when receiving direct message" section to FAQs in README
- Fixes #86 

/cc @wlaurance

### CODE REVIEW

**Comment by twolfson** [comment]
@wlaurance I have fixed up the lint errors

**Comment by twolfson** [comment]
This should also be published as a patch version so that `npm's` README has the same updates. Taking care of that now =/

**Comment by twolfson** [comment]
Released in `2.2.1`

**Comment by wlaurance** [comment]
Ah! I forget that npm needs a readme update :(

**Pull request merged**
