### PR TITLE
Added integration tests

### PR DESCRIPTION
**Pull request by twolfson**
In order to properly patch #96, we need support for integration tests. Otherwise, iterating and reproducing edge cases will significantly slow down development. This PR adds support for that by adding in Selenium and setting up a basic integration test.

In this PR:

- Added Selenium download/setup scripts
- Added integration tests
- Added documentation for testing and integration tests

/cc @wlaurance

### CODE REVIEW

**Comment by twolfson** [comment]
Hmm, the tests seem to be failing but I am out of time for tonight. I will take another look tomorrow.

**Comment by twolfson** [comment]
Alright, tests are good now. We needed to start an X11 server in Travis CI.

**Comment by twolfson** [comment]
This PR had some spaces lurking in it. This has been fixed.

**Comment by wlaurance** [comment]
OK cool. I see this is a dependency of #110. I will merge/release tomorrow (well today, in the morning)

**Comment by twolfson** [comment]
I can also merge/release. All I need is a :+1: or "looks good to me" =P

But releasing for me right now isn't so great either (in case something breaks in 1 or 2 hours).

**Comment by wlaurance** [comment]
:+1: =P

**Pull request merged**
