### PR TITLE
Added notification badges to sidebar

### PR DESCRIPTION
**Pull request by twolfson**
**Depends on #91 due to using dev tools for development**

One of the most requested features is notification badges. Now that the React refactor is over, we can easily add them in. In this PR:

- Added in notification badges to sidebar
- Refactored CSS to make it more OOCSS-like

**Notes:**

It looks like the official Slack client has an unread state for teams (grey triangle on left of badges). However, our current implementation doesn't distinguish unread notifications from other ones. I will open up another issue to get the implementation right.

Here's a screenshot of the final result:

selection_143

/cc @wlaurance

### CODE REVIEW

**Comment by mathieumg** [comment]
Haven't tested yet, but :+1 :grin:

**Comment by wlaurance** [comment]
Working on a new release. Hit a GH rate limit problem from my current IP address at a co-working space :/

**Comment by mathieumg** [comment]
> Hit a GH rate limit problem from my current IP address at a co-working space

Woah, worker bees in there!

**Comment by wlaurance** [comment]
```bash
curl https://api.github.com/rate_limit
```
```json
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 0,
      "reset": 1435282558
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1435279951
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 0,
    "reset": 1435282558
  }
}
```

**Comment by mathieumg** [comment]
Huh, that's in a little while... :worried:

**Comment by wlaurance** [comment]
```node
new Date(1435282558 * 1000)
Thu Jun 25 2015 18:35:58 GMT-0700 (PDT)
```

Looks like 40 minutes from now

**Comment by wlaurance** [comment]
There is a way to supply a Token for the github changes module with `-k --token`` https://github.com/lalitkapoor/github-changes.

But if @twolfson is around to make a release, that'd be great.

**Comment by wlaurance** [comment]
OK got it shipped in `v2.4.0` after the rate limit was reset.

**Comment by mathieumg** [comment]
Awesome! Will update shortly. :tada:

**Comment by mathieumg** [comment]
@wlaurance Do you know where `nw.js` stores the `localStorage`? So I can upgrade from `slack-for-linux` without having to log back in 6 teams. Thanks!

**Comment by wlaurance** [comment]
OK nice! I was just gonna say it's probably in `~/.config/slack-for-linux/`

**Comment by twolfson** [comment]
@wlaurance Yep, I was on the fence about baking in `--token` to the script due to being unable to think of a way save a token for later. I couldn't use `--auth` since I use 2FA which doesn't work with username/password only.

What are your thoughts on adding a conditional extra parameter in `release.sh`:

```bash
# If we have a GITHUB_TOKEN environment variable, generate a `--token` flag for `github-changes`
token_option=""
if test -n "$GITHUB_TOKEN"; then
  token_option="--token \"$GITHUB_TOKEN\""
fi

# Generate a new CHANGELOG
./node_modules/.bin/github-changes --title "plaidchat changelog" \
  $token_option \  # DEV: Don't quote token option as it's multiple parameters 
  --owner plaidchat # ...
```

Then, if we bump into a rate limit, we can run release with an environment variable:

```bash
GITHUB_TOKEN=abcdef ./release.sh minor
```

**Pull request merged**
