### PR TITLE
Set process title

### PR DESCRIPTION
**Pull request by wlaurance**
See #6

### CODE REVIEW

**Comment by wlaurance** [comment]
This needs to land after #41

**Comment by twolfson** [comment]
Can you elaborate on #6? I don't think we came to a conclusion there =/

**Comment by wlaurance** [comment]
Made a comment in #6

**Comment by twolfson** [comment]
Decided to close #6 for consistency purposes. The `process.title` change looks good. This PR needs a bump to pick up the `spawn` changes from `master`.

**Pull request closed without merging**
